spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.18.30.135:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.aiguigu.springcloud.entities
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #最后一次心态等待时间上线，默认90秒
    lease-expiration-duration-in-seconds: 2
    #心跳间隔时间 默认30秒
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true

